COVID DATA ANALYSIS

EXPERIMENT 20

NAME: AADIT JOSHI

25070123173

In [8]:
import pandas as pd
import numpy as np

In [11]:
data = pd.read_csv("/content/covid_19_data (2).csv")
data.head()

,SNo,ObservationDate,Province/State,Country/Region,Last Update,Confirmed,Deaths,Recovered
0,1,01/22/2020,Anhui,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
1,2,01/22/2020,Beijing,Mainland China,1/22/2020 17:00,14.0,0.0,0.0
2,3,01/22/2020,Chongqing,Mainland China,1/22/2020 17:00,6.0,0.0,0.0
3,4,01/22/2020,Fujian,Mainland China,1/22/2020 17:00,1.0,0.0,0.0
4,5,01/22/2020,Gansu,Mainland China,1/22/2020 17:00,0.0,0.0,0.0

In [ ]:
data = data.drop(['SNo','Last Update'],axis=1)
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      01/22/2020          Anhui  Mainland China        1.0     0.0        0.0
1      01/22/2020        Beijing  Mainland China       14.0     0.0        0.0
2      01/22/2020      Chongqing  Mainland China        6.0     0.0        0.0
3      01/22/2020         Fujian  Mainland China        1.0     0.0        0.0
4      01/22/2020          Gansu  Mainland China        0.0     0.0        0.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ObservationDate  306429 non-null  object
 1   Province/State   228326 non-null  object
 2   Country/Region   306429 non-null  object
 3   Confirmed        306429 non-null  float64
 4   Deaths           306429 non-null  float64
 5   Recovered        306429 non-null  float64
dtypes: float64(3), object(3)
memory usage: 14.0+ MB

In [ ]:
data.head()

  ObservationDate Province/State  Country/Region  Confirmed  Deaths  Recovered
0      01/22/2020          Anhui  Mainland China        1.0     0.0        0.0
1      01/22/2020        Beijing  Mainland China       14.0     0.0        0.0
2      01/22/2020      Chongqing  Mainland China        6.0     0.0        0.0
3      01/22/2020         Fujian  Mainland China        1.0     0.0        0.0
4      01/22/2020          Gansu  Mainland China        0.0     0.0        0.0

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 306429 entries, 0 to 306428
Data columns (total 6 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ObservationDate  306429 non-null  object
 1   Province/State   228326 non-null  object
 2   Country/Region   306429 non-null  object
 3   Confirmed        306429 non-null  float64
 4   Deaths           306429 non-null  float64
 5   Recovered        306429 non-null  float64
dtypes: float64(3), object(3)
memory usage: 14.0+ MB

In [ ]:
### Active Case
data['Active'] = data['Confirmed'] - data['Recovered'] - data['Deaths']
data.head(50)

data.iloc[50:100]

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
50,01/23/2020,Heilongjiang,Mainland China,2.0,0.0,0.0,2.0
51,01/23/2020,Henan,Mainland China,5.0,0.0,0.0,5.0
52,01/23/2020,Hong Kong,Hong Kong,2.0,0.0,0.0,2.0
53,01/23/2020,Hubei,Mainland China,444.0,17.0,28.0,399.0
54,01/23/2020,Hunan,Mainland China,9.0,0.0,0.0,9.0
55,01/23/2020,Inner Mongolia,Mainland China,0.0,0.0,0.0,0.0
56,01/23/2020,Jiangsu,Mainland China,5.0,0.0,0.0,5.0
57,01/23/2020,Jiangxi,Mainland China,7.0,0.0,0.0,7.0
58,01/23/2020,Jilin,Mainland China,1.0,0.0,0.0,1.0
59,01/23/2020,Liaoning,Mainland China,3.0,0.0,0.0,3.0
60,01/23/2020,Macau,Macau,2.0,0.0,0.0,2.0
61,01/23/2020,Ningxia,Mainland China,1.0,0.0,0.0,1.0
62,01/23/2020,Qinghai,Mainland China,0.0,0.0,0.0,0.0
63,01/23/2020,Shaanxi,Mainland China,3.0,0.0,0.0,3.0
64,01/23/2020,Shandong,Mainland China,6.0,0.0,0.0,6.0
65,01/23/2020,Shanghai,Mainland China,16.0,0.0,0.0,16.0
66,01/23/2020,Shanxi,Mainland China,1.0,0.0,0.0,1.0
67,01/23/2020,Sichuan,Mainland China,8.0,0.0,0.0,8.0
68,01/23/2020,Taiwan,Taiwan,1.0,0.0,0.0,1.0
69,01/23/2020,Tianjin,Mainland China,4.0,0.0,0.0,4.0
70,01/23/2020,Tibet,Mainland China,0.0,0.0,0.0,0.0
71,01/23/2020,Washington,US,1.0,0.0,0.0,1.0
72,01/23/2020,Xinjiang,Mainland China,2.0,0.0,0.0,2.0
73,01/23/2020,Yunnan,Mainland China,2.0,0.0,0.0,2.0
74,01/23/2020,Zhejiang,Mainland China,27.0,0.0,0.0,27.0
75,01/23/2020,NaN,Japan,1.0,0.0,0.0,1.0
76,01/23/2020,NaN,Thailand,4.0,0.0,2.0,2.0
77,01/23/2020,NaN,South Korea,1.0,0.0,0.0,1.0
78,01/23/2020,NaN,Singapore,1.0,0.0,0.0,1.0
79,01/23/2020,NaN,Philippines,0.0,0.0,0.0,0.0
80,01/23/2020,NaN,Malaysia,0.0,0.0,0.0,0.0
81,01/23/2020,NaN,Vietnam,2.0,0.0,0.0,2.0
82,01/23/2020,NaN,Australia,0.0,0.0,0.0,0.0
83,01/23/2020,NaN,Mexico,0.0,0.0,0.0,0.0
84,01/23/2020,NaN,Brazil,0.0,0.0,0.0,0.0
85,01/23/2020,NaN,Colombia,0.0,0.0,0.0,0.0
86,01/23/2020,Unknown,China,0.0,0.0,0.0,0.0
87,01/23/2020,NaN,Kiribati,0.0,0.0,0.0,0.0
88,01/24/2020,Hubei,Mainland China,549.0,24.0,31.0,494.0
89,01/24/2020,Guangdong,Mainland China,53.0,0.0,2.0,51.0
90,01/24/2020,Zhejiang,Mainland China,43.0,0.0,1.0,42.0
91,01/24/2020,Beijing,Mainland China,36.0,0.0,1.0,35.0
92,01/24/2020,Chongqing,Mainland China,27.0,0.0,0.0,27.0
93,01/24/2020,Hunan,Mainland China,24.0,0.0,0.0,24.0
94,01/24/2020,Guangxi,Mainland China,23.0,0.0,0.0,23.0
95,01/24/2020,Shanghai,Mainland China,20.0,0.0,1.0,19.0
96,01/24/2020,Jiangxi,Mainland China,18.0,0.0,0.0,18.0
97,01/24/2020,Sichuan,Mainland China,15.0,0.0,0.0,15.0
98,01/24/2020,Shandong,Mainland China,15.0,0.0,0.0,15.0
99,01/24/2020,Anhui,Mainland China,15.0,0.0,0.0,15.0

In [ ]:
### last/current date
data['ObservationDate'].max()

'12/31/2020'

In [ ]:
### Fetch the latest date data
latest_data = data[data['ObservationDate'] == data['ObservationDate'].max()]
latest_data.head()

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
191703,12/31/2020,NaN,Afghanistan,51526.0,2191.0,41727.0,7608.0
191704,12/31/2020,NaN,Albania,58316.0,1181.0,33634.0,23501.0
191705,12/31/2020,NaN,Algeria,99610.0,2756.0,67127.0,29727.0
191706,12/31/2020,NaN,Andorra,8049.0,84.0,7432.0,533.0
191707,12/31/2020,NaN,Angola,17553.0,405.0,11044.0,6104.0

In [ ]:
latest_data.shape

(763, 7)

In [ ]:
latest_data['Country/Region'].value_counts()

Country/Region
Russia                83
US                    58
Japan                 49
India                 37
Colombia              34
                      ..
Venezuela              1
Vietnam                1
West Bank and Gaza     1
Hong Kong              1
Macau                  1
Name: count, Length: 194, dtype: int64

In [ ]:
latest_data['Country/Region'].nunique()

194

In [ ]:
latest_data['Country/Region'].unique()

array(['Afghanistan', 'Albania', 'Algeria', 'Andorra', 'Angola',
       'Antigua and Barbuda', 'Argentina', 'Armenia', 'Austria',
       'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados',
       'Belarus', 'Belize', 'Benin', 'Bhutan', 'Bolivia',
       'Bosnia and Herzegovina', 'Botswana', 'Brunei', 'Bulgaria',
       'Burkina Faso', 'Burma', 'Burundi', 'Cabo Verde', 'Cambodia',
       'Cameroon', 'Central African Republic', 'Chad', 'Comoros',
       'Congo (Brazzaville)', 'Congo (Kinshasa)', 'Costa Rica', 'Croatia',
       'Cuba', 'Cyprus', 'Czech Republic', 'Denmark', 'Diamond Princess',
       'Djibouti', 'Dominica', 'Dominican Republic', 'Ecuador', 'Egypt',
       'El Salvador', 'Equatorial Guinea', 'Eritrea', 'Estonia',
       'Eswatini', 'Ethiopia', 'Fiji', 'Finland', 'France', 'Gabon',
       'Gambia', 'Georgia', 'Ghana', 'Greece', 'Grenada', 'Guatemala',
       'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 'Holy See',
       'Honduras', 'Hungary', 'Iceland', 'Indonesia', 'Iran', 'Iraq',
       'Ireland', 'Israel', 'Ivory Coast', 'Jamaica', 'Jordan',
       'Kazakhstan', 'Kenya', 'Kiribati', 'Kosovo', 'Kuwait',
       'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia',
       'Libya', 'Liechtenstein', 'Lithuania', 'Luxembourg', 'MS Zaandam',
       'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta',
       'Marshall Islands', 'Mauritania', 'Mauritius', 'Moldova', 'Monaco',
       'Mongolia', 'Montenegro', 'Morocco', 'Mozambique', 'Namibia',
       'Nepal', 'New Zealand', 'Nicaragua', 'Niger', 'Nigeria',
       'North Macedonia', 'Norway', 'Oman', 'Panama', 'Papua New Guinea',
       'Paraguay', 'Philippines', 'Poland', 'Portugal', 'Qatar',
       'Romania', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia',
       'Saint Vincent and the Grenadines', 'Samoa', 'San Marino',
       'Sao Tome and Principe', 'Saudi Arabia', 'Senegal', 'Serbia',
       'Seychelles', 'Sierra Leone', 'Singapore', 'Slovakia', 'Slovenia',
       'Solomon Islands', 'Somalia', 'South Africa', 'South Korea',
       'South Sudan', 'Sri Lanka', 'Sudan', 'Suriname', 'Switzerland',
       'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand',
       'Timor-Leste', 'Togo', 'Trinidad and Tobago', 'Tunisia', 'Turkey',
       'Uganda', 'United Arab Emirates', 'Uruguay', 'Uzbekistan',
       'Vanuatu', 'Venezuela', 'Vietnam', 'West Bank and Gaza', 'Yemen',
       'Zambia', 'Zimbabwe', 'Italy', 'Brazil', 'Russia', 'Mexico',
       'Japan', 'US', 'Canada', 'Colombia', 'Peru', 'Spain', 'India',
       'UK', 'Mainland China', 'Chile', 'Belgium', 'Netherlands',
       'Australia', 'Pakistan', 'Germany', 'Sweden', 'Ukraine',
       'Hong Kong', 'Macau'], dtype=object)

In [ ]:
## Count of cases for each country
countries = latest_data.groupby("Country/Region")[["Confirmed","Deaths","Recovered","Active"]].sum()

countries = countries.reset_index()

In [ ]:
countries

         Country/Region  Confirmed  Deaths  Recovered   Active
0           Afghanistan    51526.0  2191.0    41727.0   7608.0
1               Albania    58316.0  1181.0    33634.0  23501.0
2               Algeria    99610.0  2756.0    67127.0  29727.0
3               Andorra     8049.0    84.0     7432.0    533.0
4                Angola    17553.0   405.0    11044.0   6104.0
..                  ...        ...     ...        ...      ...
189             Vietnam     1465.0    35.0     1325.0    105.0
190  West Bank and Gaza   138004.0  1400.0   117183.0  19421.0
191               Yemen     2099.0   610.0     1394.0     95.0
192              Zambia    20725.0   388.0    18660.0   1677.0
193            Zimbabwe    13867.0   363.0    11250.0   2254.0

[194 rows x 5 columns]

In [ ]:
countries[countries['Country/Region']=="Mainland China"]

     Country/Region  Confirmed  Deaths  Recovered  Active
107  Mainland China    87071.0  4634.0    82064.0   373.0

In [ ]:
countries[countries['Country/Region']=="US"]

    Country/Region   Confirmed    Deaths  Recovered      Active
181             US  20099363.0  352163.0        0.0  19747200.0

In [ ]:
# Cases in India
countries[countries['Country/Region']=="India"]

   Country/Region   Confirmed    Deaths  Recovered    Active
78          India  10266674.0  148738.0  9860280.0  257656.0

In [ ]:
countries['Country/Region']=="Mainland China"

0      False
1      False
2      False
3      False
4      False
       ...
189    False
190    False
191    False
192    False
193    False
Name: Country/Region, Length: 194, dtype: bool

In [ ]:
### Plot on World Map

import plotly.express as px

In [ ]:
world_map = px.choropleth(countries,locations="Country/Region",locationmode="country names",
                          color="Confirmed",color_continuous_scale="reds",range_color=[0,10000000])
world_map

In [ ]:
world_map = px.choropleth(countries,locations="Country/Region",locationmode="country names",
                          color="Recovered",color_continuous_scale="greens",range_color=[0,10000000])
world_map

In [ ]:
### count of cases datewise
total_cases = data.groupby("ObservationDate")[["Confirmed","Deaths","Recovered","Active"]].sum().reset_index()
total_cases

    ObservationDate   Confirmed     Deaths   Recovered      Active
0        01/01/2021  84092619.0  1834675.0  47313005.0  34944939.0
1        01/02/2021  84718978.0  1843108.0  47614297.0  35261573.0
2        01/03/2021  85251774.0  1850449.0  47882779.0  35518546.0
3        01/04/2021  85805892.0  1860598.0  48173187.0  35772107.0
4        01/05/2021  86546014.0  1875953.0  48488548.0  36181513.0
..              ...         ...        ...         ...         ...
489      12/27/2020  80912611.0  1771659.0  45717710.0  33423242.0
490      12/28/2020  81408934.0  1781415.0  46016136.0  33611383.0
491      12/29/2020  82073362.0  1796786.0  46369231.0  33907345.0
492      12/30/2020  82834592.0  1811843.0  46757476.0  34265273.0
493      12/31/2020  83559601.0  1825012.0  47032627.0  34701962.0

[494 rows x 5 columns]

In [ ]:
### Top countries having maximum confirmed and recovered cases

In [ ]:
top = latest_data.groupby("Country/Region")[['Confirmed','Recovered']].sum().reset_index()
top = top.sort_values(['Confirmed'],ascending=False)
top.head()

    Country/Region   Confirmed  Recovered
181             US  20099363.0        0.0
78           India  10266674.0  9860280.0
23          Brazil   7675973.0  6848844.0
143         Russia   3127347.0  2527722.0
60          France   2677666.0   200142.0

In [ ]:
top_20 = top.head(20)
top_20

     Country/Region  Confirmed  Recovered
182              US   33251939          0
78            India   27894800   25454320
23           Brazil   16471600   14496224
60           France    5719877     390878
180          Turkey    5235978    5094279
144          Russia    4995613    4616422
181              UK    4496823      15481
84            Italy    4213055    3845087
6         Argentina    3732263    3288467
64          Germany    3684672    3479700
165           Spain    3668658     150376
36         Colombia    3363061    3141549
80             Iran    2893218    2425033
140          Poland    2871371    2636675
116          Mexico    2411503    1924865
184         Ukraine    2257904    2084477
138            Peru    1947555    1897522
79        Indonesia    1809926    1659974
126     Netherlands    1671967      26810
44   Czech Republic    1660935    1617498

In [ ]:
#### India

In [ ]:
india = data[data['Country/Region']=="India"]
india

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
446,01/30/2020,NaN,India,1.0,0.0,0.0,1.0
509,01/31/2020,NaN,India,1.0,0.0,0.0,1.0
567,02/01/2020,NaN,India,1.0,0.0,0.0,1.0
629,02/02/2020,NaN,India,2.0,0.0,0.0,2.0
696,02/03/2020,NaN,India,3.0,0.0,0.0,3.0
...,...,...,...,...,...,...,...
306351,05/29/2021,Tripura,India,50739.0,507.0,43190.0,7042.0
306366,05/29/2021,Unknown,India,0.0,0.0,0.0,0.0
306377,05/29/2021,Uttar Pradesh,India,1688152.0,20208.0,1621743.0,46201.0
306378,05/29/2021,Uttarakhand,India,327112.0,6360.0,289642.0,31110.0
306406,05/29/2021,West Bengal,India,1354956.0,15268.0,1237290.0,102398.0

In [ ]:
# Find total number of states
india['Province/State'].nunique()

38

In [ ]:
# Find names of states
india['Province/State'].unique()

array([nan, 'Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadar Nagar Haveli', 'Delhi', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Ladakh', 'Madhya Pradesh', 'Maharashtra',
       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
       'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Tripura', 'Unknown', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Dadra and Nagar Haveli and Daman and Diu',
       'Lakshadweep'], dtype=object)

In [ ]:
india['Province/State'] = india['Province/State'].fillna("Unknown")

/tmp/ipykernel_16243/1748090106.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [ ]:
india['Province/State'].unique()

array(['Unknown', 'Andaman and Nicobar Islands', 'Andhra Pradesh',
       'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh',
       'Chhattisgarh', 'Dadar Nagar Haveli', 'Delhi', 'Goa', 'Gujarat',
       'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand',
       'Karnataka', 'Kerala', 'Ladakh', 'Madhya Pradesh', 'Maharashtra',
       'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha',
       'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu',
       'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand',
       'West Bengal', 'Dadra and Nagar Haveli and Daman and Diu',
       'Lakshadweep'], dtype=object)

In [ ]:
india['Province/State'].nunique()

38

In [ ]:
#india_latest_data
india_latest_data = india[india['ObservationDate'] ==india['ObservationDate'].max()]
india_latest_data

,ObservationDate,Province/State,Country/Region,Confirmed,Deaths,Recovered,Active
191893,12/31/2020,Andaman and Nicobar Islands,India,4941.0,62.0,4820.0,59.0
191894,12/31/2020,Andhra Pradesh,India,881948.0,7104.0,871588.0,3256.0
191911,12/31/2020,Arunachal Pradesh,India,16711.0,56.0,16549.0,106.0
191912,12/31/2020,Assam,India,216139.0,1043.0,211838.0,3258.0
191934,12/31/2020,Bihar,India,251348.0,1393.0,245156.0,4799.0
191968,12/31/2020,Chandigarh,India,19682.0,316.0,18967.0,399.0
191975,12/31/2020,Chhattisgarh,India,278540.0,3350.0,263251.0,11939.0
191994,12/31/2020,Dadra and Nagar Haveli and Daman and Diu,India,3375.0,2.0,3364.0,9.0
191998,12/31/2020,Delhi,India,624795.0,10523.0,608434.0,5838.0
192034,12/31/2020,Goa,India,50981.0,737.0,49313.0,931.0
192050,12/31/2020,Gujarat,India,244258.0,4302.0,229977.0,9979.0
192056,12/31/2020,Haryana,India,262054.0,2899.0,255356.0,3799.0
192063,12/31/2020,Himachal Pradesh,India,55114.0,931.0,51387.0,2796.0
192089,12/31/2020,Jammu and Kashmir,India,120744.0,1880.0,115830.0,3034.0
192092,12/31/2020,Jharkhand,India,114873.0,1027.0,112206.0,1640.0
192110,12/31/2020,Karnataka,India,918544.0,12081.0,894834.0,11629.0
192113,12/31/2020,Kerala,India,755718.0,3042.0,687104.0,65572.0
192138,12/31/2020,Ladakh,India,9447.0,127.0,9132.0,188.0
192139,12/31/2020,Lakshadweep,India,0.0,0.0,0.0,0.0
192159,12/31/2020,Madhya Pradesh,India,240947.0,3595.0,227965.0,9387.0
192165,12/31/2020,Maharashtra,India,1928603.0,49463.0,1824934.0,54206.0
192167,12/31/2020,Manipur,India,28137.0,354.0,26601.0,1182.0
192180,12/31/2020,Meghalaya,India,13408.0,139.0,13085.0,184.0
192194,12/31/2020,Mizoram,India,4204.0,8.0,4091.0,105.0
192206,12/31/2020,Nagaland,India,11921.0,79.0,11624.0,218.0
192250,12/31/2020,Odisha,India,329306.0,1871.0,325103.0,2332.0
192284,12/31/2020,Puducherry,India,38096.0,633.0,37100.0,363.0
192288,12/31/2020,Punjab,India,166239.0,5331.0,157043.0,3865.0
192298,12/31/2020,Rajasthan,India,307554.0,2689.0,295030.0,9835.0
192347,12/31/2020,Sikkim,India,5877.0,127.0,5218.0,532.0
192368,12/31/2020,Tamil Nadu,India,817077.0,12109.0,796353.0,8615.0
192372,12/31/2020,Telangana,India,286354.0,1541.0,278839.0,5974.0
192389,12/31/2020,Tripura,India,33264.0,385.0,32751.0,128.0
192404,12/31/2020,Unknown,India,0.0,0.0,0.0,0.0
192415,12/31/2020,Uttar Pradesh,India,584966.0,8352.0,562459.0,14155.0
192416,12/31/2020,Uttarakhand,India,90616.0,1504.0,84149.0,4963.0
192443,12/31/2020,West Bengal,India,550893.0,9683.0,528829.0,12381.0

In [ ]:
top_state = india_latest_data.groupby("Province/State")[['Confirmed','Recovered']].sum().reset_index()
top_state = top_state.sort_values(['Confirmed'],ascending=False)
top_state.head(20)

       Province/State  Confirmed  Recovered
20        Maharashtra  1928603.0  1824934.0
15          Karnataka   918544.0   894834.0
1      Andhra Pradesh   881948.0   871588.0
30         Tamil Nadu   817077.0   796353.0
16             Kerala   755718.0   687104.0
8               Delhi   624795.0   608434.0
34      Uttar Pradesh   584966.0   562459.0
36        West Bengal   550893.0   528829.0
25             Odisha   329306.0   325103.0
28          Rajasthan   307554.0   295030.0
31          Telangana   286354.0   278839.0
6        Chhattisgarh   278540.0   263251.0
11            Haryana   262054.0   255356.0
4               Bihar   251348.0   245156.0
10            Gujarat   244258.0   229977.0
19     Madhya Pradesh   240947.0   227965.0
3               Assam   216139.0   211838.0
27             Punjab   166239.0   157043.0
13  Jammu and Kashmir   120744.0   115830.0
14          Jharkhand   114873.0   112206.0